(function($h$$){function $g$$($a$$,$b$$,$c$$,$d$$,$e$$){this._listener=$b$$;this._isOnce=$c$$;this.context=$d$$;this._signal=$a$$;this._priority=$e$$||0}function $f$$($a$$,$b$$){if(typeof $a$$!=="function")throw Error("listener is a required param of {fn}() and should be a Function.".replace("{fn}",$b$$));}var $e$$0$$={VERSION:"0.7.4"};$g$$.prototype={active:!0,params:null,execute:function $$g$$$$execute$($a$$){var $b$$;this.active&&this._listener&&($a$$=this.params?this.params.concat($a$$):$a$$,
$b$$=this._listener.apply(this.context,$a$$),this._isOnce&&this.detach());return $b$$},detach:function $$g$$$$detach$(){return this.isBound()?this._signal.remove(this._listener,this.context):null},isBound:function $$g$$$$isBound$(){return!!this._signal&&!!this._listener},getListener:function $$g$$$$getListener$(){return this._listener},_destroy:function $$g$$$$_destroy$(){delete this._signal;delete this._listener;delete this.context},isOnce:function $$g$$$$isOnce$(){return this._isOnce},toString:function $$g$$$$toString$(){return"[SignalBinding isOnce:"+
this._isOnce+", isBound:"+this.isBound()+", active:"+this.active+"]"}};$e$$0$$.Signal=function $$e$$0$$$Signal$(){this._bindings=[];this._prevParams=null};$e$$0$$.Signal.prototype={memorize:!1,_shouldPropagate:!0,active:!0,_registerListener:function $$e$$0$$$Signal$$_registerListener$($a$$,$b$$,$c$$,$d$$){var $e$$=this._indexOfListener($a$$,$c$$);if($e$$!==-1){if($a$$=this._bindings[$e$$],$a$$.isOnce()!==$b$$)throw Error("You cannot add"+($b$$?"":"Once")+"() then add"+(!$b$$?"":"Once")+"() the same listener without removing the relationship first.");
}else $a$$=new $g$$(this,$a$$,$b$$,$c$$,$d$$),this._addBinding($a$$);this.memorize&&this._prevParams&&$a$$.execute(this._prevParams);return $a$$},_addBinding:function $$e$$0$$$Signal$$_addBinding$($a$$){var $b$$=this._bindings.length;do--$b$$;while(this._bindings[$b$$]&&$a$$._priority<=this._bindings[$b$$]._priority);this._bindings.splice($b$$+1,0,$a$$)},_indexOfListener:function $$e$$0$$$Signal$$_indexOfListener$($a$$,$b$$){for(var $c$$=this._bindings.length,$d$$;$c$$--;)if($d$$=this._bindings[$c$$],
$d$$._listener===$a$$&&$d$$.context===$b$$)return $c$$;return-1},has:function $$e$$0$$$Signal$$has$($a$$,$b$$){return this._indexOfListener($a$$,$b$$)!==-1},add:function $$e$$0$$$Signal$$add$($a$$,$b$$,$c$$){$f$$($a$$,"add");return this._registerListener($a$$,!1,$b$$,$c$$)},addOnce:function $$e$$0$$$Signal$$addOnce$($a$$,$b$$,$c$$){$f$$($a$$,"addOnce");return this._registerListener($a$$,!0,$b$$,$c$$)},remove:function $$e$$0$$$Signal$$remove$($a$$,$b$$){$f$$($a$$,"remove");var $c$$=this._indexOfListener($a$$,
$b$$);$c$$!==-1&&(this._bindings[$c$$]._destroy(),this._bindings.splice($c$$,1));return $a$$},removeAll:function $$e$$0$$$Signal$$removeAll$(){for(var $a$$=this._bindings.length;$a$$--;)this._bindings[$a$$]._destroy();this._bindings.length=0},getNumListeners:function $$e$$0$$$Signal$$getNumListeners$(){return this._bindings.length},halt:function $$e$$0$$$Signal$$halt$(){this._shouldPropagate=!1},dispatch:function $$e$$0$$$Signal$$dispatch$($a$$){if(this.active){var $b$$=Array.prototype.slice.call(arguments),
$c$$=this._bindings.length,$d$$;if(this.memorize)this._prevParams=$b$$;if($c$$){$d$$=this._bindings.slice();this._shouldPropagate=!0;do $c$$--;while($d$$[$c$$]&&this._shouldPropagate&&$d$$[$c$$].execute($b$$)!==!1)}}},forget:function $$e$$0$$$Signal$$forget$(){this._prevParams=null},dispose:function $$e$$0$$$Signal$$dispose$(){this.removeAll();delete this._bindings;delete this._prevParams},toString:function $$e$$0$$$Signal$$toString$(){return"[Signal active:"+this.active+" numListeners:"+this.getNumListeners()+
"]"}};typeof define==="function"&&define.amd?define($e$$0$$):typeof module!=="undefined"&&module.exports?module.exports=$e$$0$$:$h$$.signals=$e$$0$$})(this);
(function(){var $initializing$$=!1,$fnTest$$=/xyz/.test(function(){})?/\b_super\b/:/.*/;this.Class=function $this$Class$(){};Class.extend=function $Class$extend$($prop$$){function $Class$$(){!$initializing$$&&this.init&&this.init.apply(this,arguments)}var $_super$$=this.prototype;$initializing$$=!0;var $prototype$$=new this;$initializing$$=!1;for(var $name$$0$$ in $prop$$)$prototype$$[$name$$0$$]=typeof $prop$$[$name$$0$$]=="function"&&typeof $_super$$[$name$$0$$]=="function"&&$fnTest$$.test($prop$$[$name$$0$$])?
function($name$$,$fn$$){return function(){var $tmp$$=this._super;this._super=$_super$$[$name$$];var $ret$$=$fn$$.apply(this,arguments);this._super=$tmp$$;return $ret$$}}($name$$0$$,$prop$$[$name$$0$$]):$prop$$[$name$$0$$];$Class$$.prototype=$prototype$$;$Class$$.prototype.constructor=$Class$$;$Class$$.extend=arguments.callee;return $Class$$}})();var AtelierJS={};
(function($window$$){AtelierJS.Souvenirs={assets:{},sprites:{},sounds:{},register:function $AtelierJS$Souvenirs$register$($id$$,$ref$$){this.assets[$id$$]=$ref$$},add:function $AtelierJS$Souvenirs$add$($id$$,$sprite$$,$override$$){if(!this.sprites[$id$$]||$override$$)this.sprites[$id$$]=$sprite$$;else throw Error("Souvenir '"+$id$$+"' already exists!");},clone:function $AtelierJS$Souvenirs$clone$($id$$){if($id$$ in this.sprites)return this.sprites[$id$$].clone(!0)}};$window$$.Souvenirs=AtelierJS.Souvenirs;
AtelierJS.Curator={scenes:{},currentScene:{},nextScene:{},transitioning:!1,registerCollection:function $AtelierJS$Curator$registerCollection$($scenesArray$$,$autoStart$$){this.scenes=$scenesArray$$;$autoStart$$&&(this.switchTo($autoStart$$===!0?Object.keys(this.scenes).shift():$autoStart$$),Ticker.addListener(this))},tick:function $AtelierJS$Curator$tick$(){if(this.currentScene instanceof AtelierJS.Scene)this.transitioning===!0?(this.currentScene.disappear(),this.nextScene.appear()):this.transitioning===
"ready"?(this.transitioning=!1,stage.removeChild(Curator.currentScene.subStage),this.currentScene=this.nextScene):this.currentScene.update()},switchTo:function $AtelierJS$Curator$switchTo$($newScene$$){this.currentScene instanceof AtelierJS.Scene&&this.currentScene.destroy();this.currentScene=new this.scenes[$newScene$$].scene},transitionTo:function $AtelierJS$Curator$transitionTo$($nextScene$$){this.nextScene=new this.scenes[$nextScene$$].scene;this.currentScene.disappeared.add(this.endTransition);
this.nextScene.appeared.add(this.endTransition);this.transitioning=!0},endTransition:function $AtelierJS$Curator$endTransition$(){Curator.transitioning="ready"}};$window$$.Curator=AtelierJS.Curator;AtelierJS.StateMachine=function $AtelierJS$StateMachine$(){this.states={OFF:0,ON:1};this.currentState=1;this.changed=new signals.Signal;this.registerStates=function $this$registerStates$($stateArray$$){for(var $s$$=0;$s$$<$stateArray$$.length;$s$$++)this.states[$stateArray$$[$s$$].toUpperCase()]=parseInt($s$$)+
2};this.setState=function $this$setState$($state$$){this.changed.dispatch($state$$,this.currentState);if(this.states[$state$$])this.currentState=this.states[$state$$]}};AtelierJS.Scene=Class.extend({init:function(){this.subStage=new Container;stage.addChild(this.subStage);this.appeared=new signals.Signal;this.disappeared=new signals.Signal},update:function(){},addChild:function($child$$){this.subStage.addChild($child$$)},onStateChanged:function(){},appear:function(){},disappear:function(){},destroy:function(){stage.removeChild(this.subStage)},
registerStates:function($stateArray$$){if(!this.states){var $stateMachine$$=new AtelierJS.StateMachine;this.states=$stateMachine$$.states;this.currentState=$stateMachine$$.currentState;this.changed=$stateMachine$$.changed;this.changed.add(this.onStateChanged);this.registerStates=$stateMachine$$.registerStates;this.setState=$stateMachine$$.setState;this.registerStates($stateArray$$)}}})})(window);var Intro=AtelierJS.Scene.extend({init:function(){this._super();this.gir=Souvenirs.clone("gir");this.addChild(this.gir);this.gir.x=bounds.width+90;this.gir.y=bounds.height/2;this.gir.vX=2;this.gir.gotoAndPlay("walk")},appear:function(){this._super()},update:function(){this.gir.x>bounds.width/2?this.gir.x-=this.gir.vX:Curator.switchTo("PLAY")},disappear:function(){this.gir.x>-180&&(this.gir.x-=2)},destroy:function(){this._super()}});var Play=AtelierJS.Scene.extend({init:function(){this._super();this.gir=Souvenirs.clone("gir");this.gir.x=bounds.width/2;this.gir.y=bounds.height/2;this.addChild(this.gir);this.gir.gotoAndPlay("idle");$("#stage").click(function(){$("body").removeClass("taco");$("#stage").unbind("click");Curator.transitionTo("CREDITS")});$("body").addClass("taco")},appear:function(){this._super()},update:function(){mouseInside?this.gir.currentAnimation==="idle"&&this.gir.gotoAndPlay("walk"):this.gir.gotoAndPlay("idle")},
disappear:function(){this.gir.x>-180&&(this.gir.x-=2)},destroy:function(){this._super()}});var Credits=AtelierJS.Scene.extend({init:function(){this._super();this.subStage.x=bounds.width;this.credits=Souvenirs.clone("credits");this.addChild(this.credits);this.tacoArray=[];for(var $t$$=0;$t$$<=9;$t$$++){var $tempTaco$$=Souvenirs.clone("taco");this.positionTaco($tempTaco$$);this.tacoArray.push($tempTaco$$);this.addChild($tempTaco$$)}},appear:function(){this.subStage.x>0?this.subStage.x-=2:($("#stage").click(function(){Tween.get(Curator.currentScene.subStage).to({y:-bounds.height,alpha:0},
1E3,Ease.cubicOut).call(function(){$("#stage").unbind("click");Curator.switchTo("INTRO")})}),this.appeared.dispatch())},update:function(){for(var $t$$=0;$t$$<=9;$t$$++){var $tempTaco$$=this.tacoArray[$t$$];$tempTaco$$.y+=$tempTaco$$.vY;$tempTaco$$.y>bounds.height*2&&this.positionTaco($tempTaco$$)}},positionTaco:function($taco$$){$taco$$.x=45+Math.random()*(bounds.width-120);$taco$$.y=-100;$taco$$.vY=5+Math.floor(Math.random()*5);$taco$$.rotation=Math.floor(Math.random()*360)},disappear:function(){this._super()},
destroy:function(){this._super()}});var canvas,bounds,stage,loader,mouseInside,init=function $init$(){$(canvas).attr("width",$("canvas").css("width"));$(canvas).attr("height",$("canvas").css("height"));$(canvas).mouseover(function(){mouseInside=!0});$(canvas).mouseleave(function(){mouseInside=!1});bounds=new Rectangle;bounds.width=canvas.width;bounds.height=canvas.height;stage=new Stage(canvas);assembleSprites();Curator.registerCollection({INTRO:{scene:Intro},PLAY:{scene:Play},CREDITS:{scene:Credits}},!0);Ticker.addListener(window);
Ticker.useRAF=!0;Ticker.setFPS(60)};
function assembleSprites(){var $gir_shape_taco$$=new BitmapAnimation(new SpriteSheet({images:[Souvenirs.assets.girSheetImg],frames:{width:180,height:244,count:9,regX:90,regY:122},animations:{idle:[0],walk:[0,8,!0,2]}}));$gir_shape_taco$$.snapToPixel=!0;Souvenirs.add("gir",$gir_shape_taco$$);$gir_shape_taco$$=new Bitmap(Souvenirs.assets.tacoImg);$gir_shape_taco$$.regX=31;$gir_shape_taco$$.regY=50;Souvenirs.add("taco",$gir_shape_taco$$);var $g$$1_text$$=new Graphics;$g$$1_text$$.beginFill(Graphics.getRGB(176,
105,199));$g$$1_text$$.rect(0,0,bounds.width,bounds.height);$gir_shape_taco$$=new Shape;$gir_shape_taco$$.graphics=$g$$1_text$$;var $text2_textShadow$$=new Shadow(Graphics.getRGB(150,20,199),0,2,1),$g$$1_text$$=new Text("Mmmmmm tacos!","normal 32px Helvetica","#fff");$g$$1_text$$.width=bounds.width;$g$$1_text$$.textAlign="center";$g$$1_text$$.x=bounds.width/2;$g$$1_text$$.y=bounds.height/2-16;$g$$1_text$$.shadow=$text2_textShadow$$;$text2_textShadow$$=new Text("Click to start over","normal 16px Helvetica",
"#fff");$text2_textShadow$$.width=bounds.width;$text2_textShadow$$.textAlign="center";$text2_textShadow$$.x=bounds.width/2;$text2_textShadow$$.y=$g$$1_text$$.y+36;$text2_textShadow$$.alpha=0.9;var $credits$$=new Container;$credits$$.addChild($gir_shape_taco$$);$credits$$.addChild($g$$1_text$$);$credits$$.addChild($text2_textShadow$$);Souvenirs.add("credits",$credits$$)}function preloadAssets($onComplete$$){loader.addCompletionListener(!$onComplete$$?init:$onComplete$$);loader.start()}
function tick(){stage.update()}canvas=document.getElementById("stage");canvas.getContext("2d")?(loader=new PxLoader,Souvenirs.register("girSheetImg",loader.addImage("./assets/girsheet.png")),Souvenirs.register("tacoImg",loader.addImage("./assets/taco.png")),preloadAssets(!1)):$(canvas).html("Your browser doesn't support the canvas element.You're missing out!");
